### ISSUE TITLE
JavaScript issue qlik-connect

### ISSUE THREAD

**Issue by dsadkigf** [ahaydon/Qlik-Cli-Windows#147]
Hello,

Qlik-CLI was installed correctly, when i try to connect, i have this message, if anyone can help

The command executed : 

**Get-PfxCertificate .\client.pfx | Connect-Qlik  -ComputerName xxx -UserName x\y-TrustAllCerts**

 </div>
        <noscript class="error-message js-disabled">
            <div>
                <header>JavaScript is disabled.</header>
                <main><p class="jsDisabledMsg">Some functionality will not work as expected if JavaScript is disabled.
</p></main>
            </div>
        </noscript>
        <form autocomplete="off" method="POST" class="login-form" id="login-form" spellcheck="false" autocorrect="off"
 autocapitalize="none">
            <div id="error-message" class="error-message" tabindex="0"></div>

            <label for="username-input">User name</label>
            <input type="text" id="username-input" name="username" class="lui-input qlik-username" placeholder="domain
\user" aria-describedby="username-hint">
            <span id="username-hint" class="hidden">domain\user</span>

            <label for="password-input">Password</label>
            <input type="password" id="password-input" class="lui-input qlik-password" name="pwd">

            <input type="submit" id="loginbtn" class="lui-button qlik-submit" value="Log in" />
        </form>
    </div>

![image](https://user-images.githubusercontent.com/75833773/101885394-5f038280-3b9a-11eb-8038-d20d90b604d6.png)

**Comment by Nillth** [comment]
rather than pipelining the certificate into the Connect-Qlik function try the following.
```PowerShell
$Cert = Get-PfxCertificate '.\client.pfx'
Connect-Qlik -Computername xxx -Username "x\y" -TrustAllCerts -Certificate $Cert
```

**Comment by dsadkigf** [comment]
Hello,

Thanks, unfortunately I still have the same error.

**Comment by Nillth** [comment]
ok, so this is probably caused by the IE settings (PowerShells Invoke-WebRequest uses IE in the background) 
if you put the Server address into IE does it work? e.g. https://xxx/qmc 
try adding the Site address to the Trusted Sites in IE and then trying the code again

**Comment by ahaydon** [comment]
The issue is that it's connecting to the proxy when it should be connecting directly to the QRS. Try the Connect-Qlik command again with the -Verbose switch, this will give more output so we can see why it's using the proxy port when a certificate has been provided.

The command should use port 4242 when a certificate is provided and 443 in all other cases, but the response you are getting is the login form from the proxy so it must be using the wrong port.

**Comment by dsadkigf** [comment]
Hi @ahaydon 

Executed with -Verborse : 

![image](https://user-images.githubusercontent.com/75833773/104575405-57cb0b00-5657-11eb-8014-9e1b243aee20.png)

I'll try what @Nillth said

Thank you

**Comment by ahaydon** [comment]
It's interesting that the certificate name is blank, it should say "Using certificate QlikClient and user ..."

It seems there may be a problem with the certificate, if you run the command `Get-PfxCertificate .\client.pfx` does it show the details of the certificate?

As it's not finding a certificate it is falling back to connecting via the proxy, and that's why you get the login form returned.

**Comment by dsadkigf** [comment]
the command Get-PfxCertificate show Thumbprint and subject yes.
I removed the https from Computername parameter and it seems to be working

Thank you
