### ISSUE TITLE
Get-QlikTask missing ID parameter

### ISSUE THREAD

**Issue by aburnsy** [ahaydon/Qlik-Cli-Windows#167]
Params listed are filter, full and raw. ID is not listed.

id is used within the code however

    PROCESS {
        $path = "/qrs/task"
        If ( !$raw ) {
            If ( $id ) { $path += "/$id" }

Also mentioned in documentation here: https://ahaydon.github.io/Qlik-Cli-Windows/Get-QlikTask.html

**Comment by aburnsy** [comment]
Apologies, after looking at the API spec for /task, I can see no ID param provided there. So perhaps, its just a matter of removing this from documentation. 
https://help.qlik.com/en-US/sense-developer/May2021/APIs/RepositoryServiceAPI/index.html?page=628

**Comment by ahaydon** [comment]
This is an issue with the Qlik-Cli documentation rather than with Qlik Sense. The task endpoint is unusual in that it returns resources of multiple types, reloadTask, userSyncTask, etc. It is provided as a way to find tasks of all types, but if you know the ID then you should use the appropriate endpoint/command for the task type.

Thanks for reporting this, I will ensure to get the documentation updated.

**Comment by ahaydon** [comment]
The documentation is now up to date.
