### ISSUE TITLE
Exporting community sheets with app?

### ISSUE THREAD

**Issue by lthocoa** [ahaydon/Qlik-Cli-Windows#171]
Would it be possible to export an app with the community sheets?

I use Qlik-Cli extensively to move apps from production to test environments and it would be awesome to move the community sheets with the app for testing. No need to maintain ownership, just it's approval status as a community sheet in the new environment so it can be tested.

**Comment by ahaydon** [comment]
It is not possible to export an app with community content, and even if you could the published/approval status is not stored in the QVF so this would be lost on export. The published/approved/owner information is stored in the repository database.

There is a workaround that can be used. You can duplicate an app using the Copy-QlikApp command, this will duplicate the app with only the base sheets. You can then use the Switch-QlikApp command to replace the new app with the original, this command copies all sheets from the source app, not just the base sheets. Since the new app is not published, all sheets will be base sheets and owned by the user that created the copy.

If you need to un-approve and unpublish the sheets after moving the app to another environment this will need to be done after publishing it to a stream. You can use the engineObjectId of each sheet in the repository to match them between the apps even on different environments, this is the ID of the object in the QVF so it does not change when copying or exporting.
