### ISSUE TITLE
New-QlikNode success, but throws error

### ISSUE THREAD

**Issue by pajo79** [ahaydon/Qlik-Cli-Windows#189]
I successfully create a node using Qlik-Cli. However, even if the node is created with the correct config I receive a error message:

Invoke-RestMethod : The remote server returned an error: (400) Bad Request.
At C:\Program Files\WindowsPowerShell\Modules\Qlik-Cli\1.21.1\functions\core.ps1:66 char:23
+ ... $result = Invoke-RestMethod @paramInvokeRestMethod @params
+ CategoryInfo : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
+ FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

Command: New-QlikNode -hostname testHostName -name devnode -nodePurpose Development -verbose

Originally reported in https://community.qlik.com/t5/Deployment-Management/Qlik-Cli-creating-node/m-p/1950623#M22602

**Comment by ahaydon** [comment]
There are two steps in the New-QlikNode command, the first is creating the node configuration, the second step is pushing the certificates to the node. It is most likely failing to push the certificates, this is usually caused by networking issues. Check that the central node can reach the rim node on port 4444, you can do this using the following command.
```powershell
Test-NetConnection rimnodehostname -Port 4444
```
