### ISSUE TITLE
Importing app that has a double quotes in its name

### ISSUE THREAD

**Issue by itsik85** [ahaydon/Qlik-Cli-Windows#190]
Hi,

I'm trying to import an app that has a double quotes in its name. Like this:

$appName = "myMod"el"
Import-QlikApp -upload -name $appName -file "test.qvf"

The running falls on a certain error.
I debugged it and found that it fails on the file functions\core.ps1 on line 60.

Of course I tried to escape the quotes with `"
Like this: $appName = "myMod`"el"
But it also failed...

Please your help...

Thank you very much!

**Comment by Nillth** [comment]
if the name is a static string, try using single quotes.
$appName = 'myMod"el'

**Comment by itsik85** [comment]
Hi Nillth,

I tried this already:
$appName = 'myMod"el'
Import-QlikApp -upload -name $appName -file "test.qvf"

It also failed...

**Comment by Nillth** [comment]
I have had a further look at this,
While you can use a single quote in the name of a App you cannot use a double quote. 
Testing this via the GUI in the QMC shows that the double quote character is one of the characters that cannot be used in the name of a App.
![image](https://user-images.githubusercontent.com/22066262/180648841-03c1021d-5983-43db-b5e9-05ca8a36e29a.png)
So this is not a issue in the PowerShell module, but a limitation in the platform caused by the use a of a prohibited character.
